### ISSUE TITLE
Cython dependency

### ISSUE THREAD

**Issue by Zeeno-atl** [idiap/bob#198]
Bob.io.base has dependency not only on HDF5, but also on h5py, which has dependency on Cython.

I was unable to install bob.io.base and all packages that depend on it using easy_install, pip or zc.buildout . This dependency is not listed in https://github.com/idiap/bob/wiki/Dependencies in the required software section, nor in the shell command for installing.

**Comment by siebenkopf** [comment]
I am pretty sure that bob.io.base has no dependency on h5py. We have our own python bindings for HDF5.

Could you please specify more details, like the operating system and the python version you are using?

**Comment by anjos** [comment]
It would also be good that:

1. You used our bob-devel mailing list for general problems before a bug is submitted (find it through our home page, please).
2. You submitted your installation logs showing the problem

**Comment by Zeeno-atl** [comment]
I am sorry for being too enthusiastic. You are right. I am not able to install bob.io.base anyway. Using easy_install to install bob.io.base gives me error (also pip or zc.buildout doesn't work) and only HDF5 dependency is listed, so I thought I have solved it.

My machine is Lubuntu 14.10 and the log is here:
```
/usr/local/lib/python2.7/dist-packages/setuptools-12.0.3-py2.7.egg/pkg_resources/__init__.py:2510: PEP440Warning: 'python-apt (0.9.3.10ubuntu1)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
/usr/local/lib/python2.7/dist-packages/setuptools-12.0.3-py2.7.egg/pkg_resources/__init__.py:2510: PEP440Warning: 'pygame (1.9.1release)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
Searching for bob.io.base
Reading https://pypi.python.org/simple/bob.io.base/
Best match: bob.io.base 2.0.2
Downloading https://pypi.python.org/packages/source/b/bob.io.base/bob.io.base-2.0.2.zip#md5=c7d5342fdbbc4c83ec20f636d696d681
Processing bob.io.base-2.0.2.zip
Writing /tmp/easy_install-7QpEbi/bob.io.base-2.0.2/setup.cfg
Running bob.io.base-2.0.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-7QpEbi/bob.io.base-2.0.2/egg-dist-tmp-yN9ph9
Traceback (most recent call last):
  File "/usr/local/bin/easy_install", line 9, in <module>
    load_entry_point('setuptools==12.0.3', 'console_scripts', 'easy_install')()
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 2244, in main
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 373, in run
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 622, in easy_install
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 652, in install_item
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 837, in install_eggs
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 1065, in build_and_install
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 1051, in run_setup
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 238, in run_setup
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 191, in setup_context
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 162, in save_modules
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 137, in resume
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 150, in save_modules
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 191, in setup_context
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 235, in run_setup
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 265, in run
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 234, in runner
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 46, in _execfile
  File "/tmp/easy_install-7QpEbi/bob.io.base-2.0.2/setup.py", line 134, in <module>
  File "/tmp/easy_install-7QpEbi/bob.io.base-2.0.2/setup.py", line 58, in __init__
IndexError: list index out of range
```
Looks like self.include_directories is empty, but after hardcoding path doesn't solve the issue. Than exceptioin 'pkg_resources.DistributionNotFound: zc.buildout==2.3.1' is thrown even though I am sure, that zc.buildout is installed as /usr/local/lib/python2.7/dist-packages/zc.buildout-2.3.1-py2.7.egg

I know it should be in mailing list now. If you close this issue and mark it as invalid, I will post it in mailing list.

**Comment by anjos** [comment]
There are some misunderstandings here.

1. If you decide to go through the zc.buildout way, then you need it. Otherwise, there is no direct dependence between Bob and zc.buildout. If you are using pip/easy_install, then you definitely don't need it.

The zc.buildout way is the most possible automatic way to get Bob on your machine. All will be downloaded and installed automagically.

2. If you decide this is unsuitable for your needs, you should use pip. I'd particularly avoid using easy_install - it is an old tool full of bugs.

3. If you decide to use pip, than please notice pip cannot, in a single shot, install all of our python bindings. The reason is that there are build dependencies between some of our modules and pip does not reset the environment after each package has been installed, while it is installing them. So, you'll need to install one package after the other by hand. You **must** respect the good order or you may find weird surprises. The correct order leading to `bob.io.base` is encoded here (https://github.com/idiap/bob/blob/master/requirements0.txt).

In your case, the right order is:

bob.extension
bob.blitz
bob.core
bob.io.base

So, you should do

```sh
$ pip install bob.extension #optional
$ pip install bob.blitz
$ pip install bob.core
$ pip install bob.io.base
```

The first package is optional because it is pure python, so it will work OK. The remaining packages need to be installed in this order because `bob.io.base` has a C++ build dependence on `bob.core`, which has a C++ build dependence on `bob.blitz`.

This is explained in details in our installation guide: https://github.com/idiap/bob/wiki/Installation#using-pip-for-experts

Please move any other discussion on the subject to our mailing list - more people may benefit from it this way.

**Comment by siebenkopf** [comment]
Anyways, the installation should not fail by raising this exception in the setup.py of bob.io.base. If include_directories is empty, we should not index the list. It might be that bob.extension.pkgconfig is not working as expected.
