### ISSUE TITLE
AssertionError: blitz version is not >= `0.10'

### ISSUE THREAD

**Issue by xiaochao** [idiap/bob#223]
version:bob.blitz-2.0.9

**Comment by siebenkopf** [comment]
Could you please be more precise? Which operating system do you have?  Did you follow the installation instructions? Which command line did you run to obtain this error message?

**Comment by xiaochao** [comment]
i follow the installation instructions https://github.com/idiap/bob/wiki/Installation
when i run:./bin/buildout

Writing /tmp/easy_install-drAmi4/bob.blitz-2.0.9/setup.cfg
Running bob.blitz-2.0.9/setup.py bdist_egg --dist-dir /tmp/easy_install-drAmi4/bob.blitz-2.0.9/egg-dist-tmp-gdoKGo
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/python2.7/lib/python2.7/site-packages/setuptools-18.8.1-py2.7.egg/setuptools/command/easy_install.py", line 2288, in main
  File "/usr/local/python2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/python2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/python2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/python2.7/lib/python2.7/site-packages/setuptools-18.8.1-py2.7.egg/setuptools/command/easy_install.py", line 390, in run
  File "/usr/local/python2.7/lib/python2.7/site-packages/setuptools-18.8.1-py2.7.egg/setuptools/command/easy_install.py", line 620, in easy_install
  File "/usr/local/python2.7/lib/python2.7/site-packages/setuptools-18.8.1-py2.7.egg/setuptools/command/easy_install.py", line 669, in install_item
  File "/usr/local/python2.7/lib/python2.7/site-packages/setuptools-18.8.1-py2.7.egg/setuptools/command/easy_install.py", line 852, in install_eggs
  File "/usr/local/python2.7/lib/python2.7/site-packages/setuptools-18.8.1-py2.7.egg/setuptools/command/easy_install.py", line 1080, in build_and_install
  File "/usr/local/python2.7/lib/python2.7/site-packages/setuptools-18.8.1-py2.7.egg/setuptools/command/easy_install.py", line 1066, in run_setup
  File "/usr/local/python2.7/lib/python2.7/site-packages/setuptools-18.8.1-py2.7.egg/setuptools/sandbox.py", line 242, in run_setup
  File "/usr/local/python2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/python2.7/lib/python2.7/site-packages/setuptools-18.8.1-py2.7.egg/setuptools/sandbox.py", line 195, in setup_context
  File "/usr/local/python2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/python2.7/lib/python2.7/site-packages/setuptools-18.8.1-py2.7.egg/setuptools/sandbox.py", line 166, in save_modules
  File "/usr/local/python2.7/lib/python2.7/site-packages/setuptools-18.8.1-py2.7.egg/setuptools/sandbox.py", line 141, in resume
  File "/usr/local/python2.7/lib/python2.7/site-packages/setuptools-18.8.1-py2.7.egg/setuptools/sandbox.py", line 154, in save_modules
  File "/usr/local/python2.7/lib/python2.7/site-packages/setuptools-18.8.1-py2.7.egg/setuptools/sandbox.py", line 195, in setup_context
  File "/usr/local/python2.7/lib/python2.7/site-packages/setuptools-18.8.1-py2.7.egg/setuptools/sandbox.py", line 239, in run_setup
  File "/usr/local/python2.7/lib/python2.7/site-packages/setuptools-18.8.1-py2.7.egg/setuptools/sandbox.py", line 269, in run
  File "/usr/local/python2.7/lib/python2.7/site-packages/setuptools-18.8.1-py2.7.egg/setuptools/sandbox.py", line 238, in runner
  File "/usr/local/python2.7/lib/python2.7/site-packages/setuptools-18.8.1-py2.7.egg/setuptools/sandbox.py", line 46, in _execfile
  File "/tmp/easy_install-drAmi4/bob.blitz-2.0.9/setup.py", line 72, in <module>
  File "/root/work/eggs/bob.extension-2.2.1-py2.7.egg/bob/extension/__init__.py", line 368, in __init__
    pkgs = check_packages(packages)
  File "/root/work/eggs/bob.extension-2.2.1-py2.7.egg/bob/extension/__init__.py", line 64, in check_packages
    assert p >= splitreq[2], "%s version is not >= `%s'" % (p.name, splitreq[2])
AssertionError: blitz version is not >= `0.10'
bob.buildout.extension: An error occurred when trying to install bob.blitz 2.0.9. Look above this message for any errors that were output by easy_install.

**Comment by anjos** [comment]
I'm guessing here, but I think you have a quite old distribution, which still contains Blitz++.

Since a few weeks now, we have deprecated all binary distributions in favor of a Conda-based build:

https://github.com/idiap/bob/wiki/Binary-Installation

Could you please try to setup that instead?

PS: I suggest we move this discussion to our mailing list: https://groups.google.com/forum/?fromgroups#!forum/bob-devel
